#!/usr/bin/env node
/**
 * Session Summary Hook - SessionEnd
 * 
 * Generates a summary of the session for knowledge retention.
 * Logs what was accomplished, key decisions, and open questions.
 * 
 * Usage: Hook receives session context via stdin as JSON.
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const SUMMARY_DIR = path.join(process.cwd(), '.qwen', 'session-summaries');

async function main() {
  const rl = readline.createInterface({ input: process.stdin });
  let input = '';
  
  for await (const line of rl) {
    input += line;
  }
  
  let context;
  try {
    context = JSON.parse(input);
  } catch (e) {
    process.exit(0);
    return;
  }
  
  // Create summary directory if needed
  if (!fs.existsSync(SUMMARY_DIR)) {
    fs.mkdirSync(SUMMARY_DIR, { recursive: true });
  }
  
  // Generate summary file with timestamp
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const summaryFile = path.join(SUMMARY_DIR, `session-${timestamp}.md`);
  
  // Try to get git changes for the session
  let gitChanges = '';
  try {
    gitChanges = execSync('git diff --stat HEAD 2>/dev/null || echo "No git repo or no changes"', { encoding: 'utf8' });
  } catch {
    gitChanges = 'Could not retrieve git changes';
  }
  
  const summary = `# Session Summary - ${timestamp}

## Session Context
- **Timestamp**: ${new Date().toISOString()}
- **Working Directory**: ${process.cwd()}

## Changes Made
\`\`\`
${gitChanges.trim()}
\`\`\`

## Notes
<!-- Add key decisions, architecture choices, and open questions here -->

---
*Auto-generated by session-summary hook*
`;
  
  fs.writeFileSync(summaryFile, summary, 'utf8');
  
  const output = {
    decision: 'allow',
    hookSpecificOutput: {
      additionalContext: `[SESSION SUMMARY] Summary saved to: ${summaryFile}`
    }
  };
  
  console.log(JSON.stringify(output));
  process.exit(0);
}

main().catch(() => process.exit(0));
